stages:
  - build
  - test
  # - integrate

default:
  image: continuumio/anaconda3:latest

## helpful YAML anchors
## for details, see https://gitlab.hzdr.de/help/ci/yaml/README.md#yaml-anchors-for-before_script-and-after_script

.cpuonly_setup: &cpuonly_setup
  - uname -a
  - env
  - pwd && ls
  - which conda && conda --version
  - which pip && pip --version
  - apt-get install -q -y gcc g++ python3-dev && apt-get clean
  - export PIP_CACHE_DIR="/opt/cache/pip" #unclear why to use this, https://beenje.github.io/blog/posts/gitlab-ci-and-conda/
  - conda env create -f cpu-env.yml #defines n2gem-cpu environment
  - source activate n2gem-cpu
  
.cuda_setup: &cuda_setup
  - uname -a
  - env
  - pwd && ls
  - which conda && conda --version
  - which pip && pip --version
  - apt-get install -q -y gcc g++ python3-dev && apt-get clean
  - export PIP_CACHE_DIR="/opt/cache/pip" #unclear why to use this, https://beenje.github.io/blog/posts/gitlab-ci-and-conda/
  - conda env create -f gpu-env.yml #defines n2gem-gpu environment
  - source activate n2gem-gpu

## build stage
check_cpu_env:
  stage: build
  before_script:
    - *cpuonly_setup
  script:
    #- python -m pip install faiss-cpu numpy
    #- python -m pip install torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
    - python ./setup.py install
    - python -m pytest --co

check_gpu_env:
  stage: build
  tags:
    - intel
    - cuda
  before_script:
    - *cuda_setup
  script:
    #- python -m pip install faiss-gpu numpy
    #- python -m pip torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
    - python ./setup.py install 
    - python -m pytest --co

## test stage

cpu_tests:
  stage: test
  before_script:
    - *cpuonly_setup
  script:
    - python -m pytest tests/
  needs: ["check_cpu_env"]

gpu_tests:
  stage: test
  tags:
    - intel
    - cuda
  before_script:
    - *cuda_setup
  script:
    - python -m pytest tests/
  needs: ["check_gpu_env"]

